### ISSUE TITLE
Getting an error memory

### ISSUE THREAD

**Issue by Doomwhite** [Codrax/iBroadcast-For-Windows#2] opened 2023-05-27 23:58 UTC
I'm on a windows 10, I logged in the account and am getting this error:
![image](https://github.com/Codrax/iBroadcast-For-Windows/assets/40442835/e87851ec-2bfb-4ca3-b584-f47b47a6f662)

**Comment by Doomwhite** [comment] 2023-05-28 00:00
I assume the dependencies in the README are for building the app, or are they also required for running it?

**Comment by Codrax** [comment] 2023-05-28 10:36
Yes, that is correct. I will try to add a logging feature to find the source of the issue.

**Comment by Codrax** [comment] 2023-06-03 09:00
@Doomwhite I uploaded the new version. When running the app, use the "-logging" parameter and the app will dump a log on your desktop.
It is also possible the bug has been fixed in this version, depending on what caused It.

Please let me know If the issue persists and provide the log if so.

**Comment by Doomwhite** [comment] 2023-06-03 14:21
The errors are still there, unfortunately, here are the logs: 
[iBroadcast Log.txt](https://github.com/Codrax/iBroadcast-For-Windows/files/11642957/iBroadcast.Log.txt)
I had to kill the process, cuz I found no way to close it normally.

**Comment by Codrax** [comment] 2023-06-03 16:15
Alright. Since I can't pinpoint the issue. Here is another version of the application:
https://drive.google.com/file/d/1eXONd-ROzJzmUXzQTsy91h3K3tTby1vJ/view?usp=sharing

This will have additional information in the log.

**Comment by Doomwhite** [comment] 2023-06-03 16:22
Ok, it looks like the error occurs whenever I click in the home section.
[iBroadcast Log.txt](https://github.com/Codrax/iBroadcast-For-Windows/files/11643194/iBroadcast.Log.txt)

**Comment by Doomwhite** [comment] 2023-06-03 16:23
Also "Your playlists" maybe something to do with the loading of the items?

**Comment by Codrax** [comment] 2023-06-03 16:38
Were you able to use and interact with the app? Or did It crash when opening?

**Comment by Codrax** [comment] 2023-06-03 16:58
I think the issue could be fixed now, but just in case I added some extra logging information. Please try this new version

https://drive.google.com/file/d/1PS3tJi8aetvt1uQEfG2KZe2IfiSjgqPD/view?usp=sharing

**Comment by Doomwhite** [comment] 2023-06-03 17:21
> Were you able to use and interact with the app? Or did It crash when opening?

Yeah, if I click fast in the other sections, I can, I tried your version, same problem in the home.
[iBroadcast Log.txt](https://github.com/Codrax/iBroadcast-For-Windows/files/11643309/iBroadcast.Log.txt)

**Comment by Codrax** [comment] 2023-06-03 17:38
I can't seem to fix the Issue as It's either a problem with your account or your PC.
Since I can't reproduce the problem on my own machine, It's virtually impossible to diagnose the issue.

I can only see 2 ways to fix the issue. Either you install Delphi 11 on your device and try to diagnose the issue yourself. Or, If you are comfortable with this. You could give me access to your library by uploading the `%localappdata%\CodrutSoftware\Cods iBroadcast\login.token` file. The token is read-only. The app can't edit the library, only play music and view It. But I understand If you are not comfortable with this approach.

**Comment by Doomwhite** [comment] 2023-06-03 17:47
> I can't seem to fix the Issue as It's either a problem with your account or your PC. Since I can't reproduce the problem on my own machine, It's virtually impossible to diagnose the issue.
> 
> I can only see 2 ways to fix the issue. Either you install Delphi 11 on your device and try to diagnose the issue yourself. Or, If you are comfortable with this. You could give me access to your library by uploading the `%localappdata%\CodrutSoftware\Cods iBroadcast\login.token` file. The token is read-only. The app can't edit the library, only play music and view It. But I understand If you are not comfortable with this approach.
Add me on discord: DooMWhite#7653

**Comment by Codrax** [comment] 2023-06-03 18:01
@Doomwhite I sent It.

**Comment by Codrax** [comment] 2023-06-03 18:37
The issue, which was caused by a access violation in the playlist length calculation, has been fixed in iBroadcast for Windows 1.4.9

**Comment by Codrax** [comment] 2023-06-03 18:45
The issue, which was caused by a access violation in the playlist length calculation, has been fixed in iBroadcast for Windows 1.4.9

**Closed as completed by Codrax** 2023-06-03 18:45 UTC
