### ISSUE TITLE
Application gets stuck on "loading tracks"

### ISSUE THREAD

**Issue by theferret94** [Codrax/iBroadcast-For-Windows#3] opened 2023-08-13 10:42 UTC
Application gets stuck on the loading tracks page. I have left it for about 25mins with no luck. I can force offline mode and it will load the program however.

I have tried running compatibility troubleshooter to run in Windows 8 compatibility mode (installation file doesnt seem to work unless I do that too) and also as administrator with the same results.

Have tried uninstalling and re-installing
Issue has persisited accross multiple versions

Windows 11 Home x64

[iBroadcast Log.txt](https://github.com/Codrax/iBroadcast-For-Windows/files/12329329/iBroadcast.Log.txt)

**Comment by Codrax** [comment] 2023-08-13 11:29
The installer does not work without compatability settings? Does It give some sort of error?

It's odd, since I compiled It for Windows 10, and It works on my machine.

**Comment by theferret94** [comment] 2023-08-13 12:24
When I try to run the installer nothing happens, but if i troubleshoot compatibility and run it for Windows 8, it works. (Could just be something on my end). Once it has installed it opens as normal (without compatiability settings), just gets stuck on the loading tracks screen

**Comment by theferret94** [comment] 2023-08-13 12:42
I have tried on another Windows 11 machine, the installer runs, just brings up the defender smartscreen windows, installs fine when I accept that. Still gets stuck on the loading tracks screen though

**Comment by Codrax** [comment] 2023-08-13 13:22
I will investigate this issue tomorrow. Based on the logs, I may have a idea where the problem may originate from.

**Comment by theferret94** [comment] 2023-08-14 04:40
No worries, if there's anything you want me to do to help, let me know!

**Comment by Codrax** [comment] 2023-08-14 08:10
Hello again. I have diagnosed the issue and concluded that the issue is not with the application Itself, but some unexpected settings in your broadcast library. If you are willing to help me, I will send you a beta version of the application which will export all POST requests that the application receives to a file.

Do you have a discord? If so, please add me `codrut1001`.

**Comment by Codrax** [comment] 2023-08-14 13:23
This bug has now been resolved in version 1.6.3.

**Closed as completed by Codrax** 2023-08-14 13:23 UTC
