### ISSUE TITLE
Stuck on "Loading library status..." after inserting an API token.

### ISSUE THREAD

**Issue by Sunhealer** [Codrax/iBroadcast-For-Windows#9] opened 2024-05-10 09:55 UTC
**Describe the bug**
The application becomes stuck on "Loading library status..." after inserting an API token.

**To Reproduce**
1. Launch Cods iBroadcast
2. Enter my API token
3. Get stuck on "Loading library status..."

**Expected behavior**
Unknown, I just installed the application, and this bug appeared the first time I launched it.

**Screenshots**
![image](https://github.com/Codrax/iBroadcast-For-Windows/assets/76262256/febd9c8a-9b91-4355-9379-b83a37854185)

**Desktop (please complete the following information):**
Edition - Windows 11 Pro
Version - 23H2
Installed on - ‎06/‎05/‎2024
OS build - 22631.3447
Experience - Windows Feature Experience Pack 1000.22688.1000.0

**Additional context**
[iBroadcast Log.txt](https://github.com/Codrax/iBroadcast-For-Windows/files/15273348/iBroadcast.Log.txt)

**Comment by Codrax** [comment] 2024-05-10 10:08
Hello there!

Did you try to run the application with the "-logging" parameter?
It should create a log file on your desktop.
If you can provide that file, I will be able to investigate the problem further . Also you could also adding "-log32" to show a visual logger.

**Comment by Codrax** [comment] 2024-05-10 10:21
Hello there! I can only assume an error reading your library occurs, this is usually caused by older formats of the json data.

To debug this further I will need the POST output of the network requests, more exactly you will need to use the "-exportpost" parameter, which will output files containing all the tracks in your library. As far as I have seen do not contain any sensitive information, except the name of your library songs of course

If you don't want to publish that information here, you can send the requests to me in private via discord at @codrut1001, or you can send me an email at codrut@codrutsoft.com

There should be a folder on your desktop with a few more files, the best way to send them is to make a compressed zip folder containing all of them.

**Comment by Sunhealer** [comment] 2024-05-10 11:27
Hi Codrax! No problem, here's the export, with both ``-exportpost`` and ``-logging`` parameters on:
[iBroadcastExport.zip](https://github.com/Codrax/iBroadcast-For-Windows/files/15274379/iBroadcastExport.zip)

I also want to note, that when launching the application this time, I was not asked to enter my API token, unlike all the other times I attempted to fix whatever was happening by just restarting the application/computer.

**Comment by Codrax** [comment] 2024-05-10 11:36
You were not asked to provide the API token because you successfully logged In. In the first log you provided, you can see just that.

I'll take a look at the zip file you provided and hopefully I can figure out what's causing the error

**Comment by Codrax** [comment] 2024-05-10 12:14
Hi again, I tried the post files you provided and the code executed successfully, all data was loaded. Are you sure you are running the latest version of iBroadcast for Windows?

If not, do you have a discord account so I can contact you directly? I'm afraid otherwise I cannot find the issue that causes your app version to hang.

**Comment by Sunhealer** [comment] 2024-05-10 12:21
I'm running 1.8.6 which I just downloaded today from your website. I got your Discord request, we'll continue there.

**Comment by Codrax** [comment] 2024-05-10 13:17
Bug caused by locale settings fixed in iBroadcast for Windows version 1.9.0

**Closed as completed by Codrax** 2024-05-10 13:17 UTC
